// <auto-generated />
using System;
using Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.AppliedJob", b =>
                {
                    b.Property<Guid>("AppliedJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppliedJobID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("AppliedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobSeekerProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppliedJobId")
                        .HasName("PK__AppliedJ__AF19BB6B4633EC01");

                    b.HasIndex("JobPostId");

                    b.HasIndex("JobSeekerProfileId");

                    b.ToTable("AppliedJob", (string)null);
                });

            modelBuilder.Entity("Domain.Models.AuthUser", b =>
                {
                    b.Property<Guid>("AuthUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuthUserID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthUserId")
                        .HasName("PK__AuthUser__7CD892D45BEA25B7");

                    b.HasIndex("SystemUserId");

                    b.ToTable("AuthUser", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Company", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("ComapnyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("IndustryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IndustryID");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("CompanyId")
                        .HasName("PK__Companie__2D971C4CF65B7287");

                    b.HasIndex("IndustryId");

                    b.HasIndex("LocationId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Domain.Models.CompanyUser", b =>
                {
                    b.Property<Guid>("CompanyUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyUserID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyID");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("JobProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CompanyUserId")
                        .HasName("PK__CompanyU__97221D13131A5E26");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobProviderId");

                    b.ToTable("CompanyUser", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Experience", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ExperienceID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("ExperienceId")
                        .HasName("PK__Experien__2F4E3469B88382B4");

                    b.ToTable("Experience", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Industry", b =>
                {
                    b.Property<Guid>("IndustryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IndustryID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IndustryId")
                        .HasName("PK__Industry__808DEC2C1A76650D");

                    b.ToTable("Industry", (string)null);
                });

            modelBuilder.Entity("Domain.Models.InterviewSchedule", b =>
                {
                    b.Property<Guid>("InterviewScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("InterviewScheduleID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("InterviewMode")
                        .HasColumnType("int");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MeetingLinkOrvenue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("MeetingLinkORvenue");

                    b.Property<DateTime>("ScheduledEndTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ScheduledStartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("InterviewScheduleId")
                        .HasName("PK__Intervie__A9EEDAB582218D17");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("JobProviderId");

                    b.ToTable("InterviewSchedule", (string)null);
                });

            modelBuilder.Entity("Domain.Models.JobApplication", b =>
                {
                    b.Property<Guid>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobApplicationID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ApplicationStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("AppliedJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobApplicationId")
                        .HasName("PK__JobAppli__BD557FE59A82D195");

                    b.HasIndex("AppliedJobId");

                    b.HasIndex("JobPostId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("Domain.Models.JobCategory", b =>
                {
                    b.Property<Guid>("JobCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("JobCategoryId")
                        .HasName("PK__JobCateg__302BAD2DFBF66B05");

                    b.ToTable("JobCategory", (string)null);
                });

            modelBuilder.Entity("Domain.Models.JobPost", b =>
                {
                    b.Property<Guid>("JobPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobPostID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CompanyID");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DeadLine")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("JobProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobcategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("JobPostId")
                        .HasName("PK__JobPost__57689C5A6950E97B");

                    b.HasIndex("CompanyId");

                    b.HasIndex("JobProviderId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("JobcategoryId");

                    b.HasIndex("LocationId");

                    b.ToTable("JobPost", (string)null);
                });

            modelBuilder.Entity("Domain.Models.JobProvider", b =>
                {
                    b.Property<Guid>("JobProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobProviderID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SystemUserID");

                    b.HasKey("JobProviderId")
                        .HasName("PK__JobProvi__A7DA6C44C42F7DB3");

                    b.HasIndex("SystemUserId");

                    b.ToTable("JobProvider", (string)null);
                });

            modelBuilder.Entity("Domain.Models.JobSeeker", b =>
                {
                    b.Property<Guid>("JobSeekerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobSeekerID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("SystemUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SystemUserID");

                    b.HasKey("JobSeekerId")
                        .HasName("PK__JobSeeke__89113A8CA7A8827E");

                    b.HasIndex("SystemUserId");

                    b.ToTable("JobSeeker", (string)null);
                });

            modelBuilder.Entity("Domain.Models.JobSeekerProfile", b =>
                {
                    b.Property<Guid>("JobSeekerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobSeekerProfileID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("About")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobSeekerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobSeekerID");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QualificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResumeUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobSeekerProfileId")
                        .HasName("PK__JobSeeke__AB9350DC3CF7A2D2");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("JobSeekerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("QualificationId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSeekerProfile", (string)null);
                });

            modelBuilder.Entity("Domain.Models.JobType", b =>
                {
                    b.Property<Guid>("JobTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("JobTypeID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("JobTypeId")
                        .HasName("PK__JobType__E1F4624D2C4B381B");

                    b.ToTable("JobType", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LocationID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("LocationId")
                        .HasName("PK__Location__E7FEA4775C8CD05F");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Qualification", b =>
                {
                    b.Property<Guid>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QualificationID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("QualificationId")
                        .HasName("PK__Qualific__C95C128A54885D72");

                    b.ToTable("Qualification", (string)null);
                });

            modelBuilder.Entity("Domain.Models.SavedJob", b =>
                {
                    b.Property<Guid>("SavedJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SavedJobID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("JobPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobSeekerProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SavedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("SavedJobId")
                        .HasName("PK__SavedJob__B7E5F37741BE66E4");

                    b.HasIndex("JobPostId");

                    b.HasIndex("JobSeekerProfileId");

                    b.ToTable("SavedJob", (string)null);
                });

            modelBuilder.Entity("Domain.Models.Skill", b =>
                {
                    b.Property<Guid>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SkillID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("SkillId")
                        .HasName("PK__Skill__DFA091E76A225C6D");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("Domain.Models.SystemUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Roles")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__SystemUs__3214EC27995361F0");

                    b.ToTable("SystemUser", (string)null);
                });

            modelBuilder.Entity("Domain.Models.AppliedJob", b =>
                {
                    b.HasOne("Domain.Models.JobPost", "JobPost")
                        .WithMany("AppliedJobs")
                        .HasForeignKey("JobPostId")
                        .IsRequired()
                        .HasConstraintName("FK_AppliedJob_JobPost");

                    b.HasOne("Domain.Models.JobSeekerProfile", "JobSeekerProfile")
                        .WithMany("AppliedJobs")
                        .HasForeignKey("JobSeekerProfileId")
                        .IsRequired()
                        .HasConstraintName("FK_AppliedJob_JobSeekerProfile");

                    b.Navigation("JobPost");

                    b.Navigation("JobSeekerProfile");
                });

            modelBuilder.Entity("Domain.Models.AuthUser", b =>
                {
                    b.HasOne("Domain.Models.SystemUser", "SystemUser")
                        .WithMany("AuthUsers")
                        .HasForeignKey("SystemUserId")
                        .IsRequired()
                        .HasConstraintName("FK_AuthUser_SystemUser");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Domain.Models.Company", b =>
                {
                    b.HasOne("Domain.Models.Industry", "Industry")
                        .WithMany("Companies")
                        .HasForeignKey("IndustryId")
                        .IsRequired()
                        .HasConstraintName("FK_Companies_Industry");

                    b.HasOne("Domain.Models.Location", "Location")
                        .WithMany("Companies")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_Companies_Location");

                    b.Navigation("Industry");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domain.Models.CompanyUser", b =>
                {
                    b.HasOne("Domain.Models.Company", "Company")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyUser_Companies");

                    b.HasOne("Domain.Models.JobProvider", "JobProvider")
                        .WithMany("CompanyUsers")
                        .HasForeignKey("JobProviderId")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyUser_JobProvider");

                    b.Navigation("Company");

                    b.Navigation("JobProvider");
                });

            modelBuilder.Entity("Domain.Models.InterviewSchedule", b =>
                {
                    b.HasOne("Domain.Models.JobApplication", "JobApplication")
                        .WithMany("InterviewSchedules")
                        .HasForeignKey("JobApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_InterviewSchedule_JobApplications");

                    b.HasOne("Domain.Models.JobProvider", "JobProvider")
                        .WithMany("InterviewSchedules")
                        .HasForeignKey("JobProviderId")
                        .IsRequired()
                        .HasConstraintName("FK_InterviewSchedule_JobProvider");

                    b.Navigation("JobApplication");

                    b.Navigation("JobProvider");
                });

            modelBuilder.Entity("Domain.Models.JobApplication", b =>
                {
                    b.HasOne("Domain.Models.AppliedJob", "AppliedJob")
                        .WithMany("JobApplications")
                        .HasForeignKey("AppliedJobId")
                        .IsRequired()
                        .HasConstraintName("FK_JobApplication_Appliedjob");

                    b.HasOne("Domain.Models.JobPost", "JobPost")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobPostId")
                        .IsRequired()
                        .HasConstraintName("FK_JobApplication_JobPost");

                    b.Navigation("AppliedJob");

                    b.Navigation("JobPost");
                });

            modelBuilder.Entity("Domain.Models.JobPost", b =>
                {
                    b.HasOne("Domain.Models.Company", "Company")
                        .WithMany("JobPosts")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_JobPost_Companies");

                    b.HasOne("Domain.Models.JobProvider", "JobProvider")
                        .WithMany("JobPosts")
                        .HasForeignKey("JobProviderId")
                        .IsRequired()
                        .HasConstraintName("FK_JobPost_JobProvider");

                    b.HasOne("Domain.Models.JobType", "JobType")
                        .WithMany("JobPosts")
                        .HasForeignKey("JobTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_JobPost_JobType");

                    b.HasOne("Domain.Models.JobCategory", "Jobcategory")
                        .WithMany("JobPosts")
                        .HasForeignKey("JobcategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_JobPost_JobCategory");

                    b.HasOne("Domain.Models.Location", "Location")
                        .WithMany("JobPosts")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_JobPost_Location");

                    b.Navigation("Company");

                    b.Navigation("JobProvider");

                    b.Navigation("JobType");

                    b.Navigation("Jobcategory");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domain.Models.JobProvider", b =>
                {
                    b.HasOne("Domain.Models.SystemUser", "SystemUser")
                        .WithMany("JobProviders")
                        .HasForeignKey("SystemUserId")
                        .IsRequired()
                        .HasConstraintName("FK_JobProvider_SystemUser");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Domain.Models.JobSeeker", b =>
                {
                    b.HasOne("Domain.Models.SystemUser", "SystemUser")
                        .WithMany("JobSeekers")
                        .HasForeignKey("SystemUserId")
                        .IsRequired()
                        .HasConstraintName("FK_JobSeeker_SystemUser");

                    b.Navigation("SystemUser");
                });

            modelBuilder.Entity("Domain.Models.JobSeekerProfile", b =>
                {
                    b.HasOne("Domain.Models.Experience", "Experience")
                        .WithMany("JobSeekerProfiles")
                        .HasForeignKey("ExperienceId")
                        .IsRequired()
                        .HasConstraintName("FK_JobSeekerProfile_Experience");

                    b.HasOne("Domain.Models.JobSeeker", "JobSeeker")
                        .WithMany("JobSeekerProfiles")
                        .HasForeignKey("JobSeekerId")
                        .IsRequired()
                        .HasConstraintName("FK_JobSeekerProfile_JobSeeker");

                    b.HasOne("Domain.Models.Location", "Location")
                        .WithMany("JobSeekerProfiles")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_JobSeekerProfile_Location");

                    b.HasOne("Domain.Models.Qualification", "Qualification")
                        .WithMany("JobSeekerProfiles")
                        .HasForeignKey("QualificationId")
                        .IsRequired()
                        .HasConstraintName("FK_JobSeekerProfile_Qualification");

                    b.HasOne("Domain.Models.Skill", "Skill")
                        .WithMany("JobSeekerProfiles")
                        .HasForeignKey("SkillId")
                        .IsRequired()
                        .HasConstraintName("FK_JobSeekerProfile_Skill");

                    b.Navigation("Experience");

                    b.Navigation("JobSeeker");

                    b.Navigation("Location");

                    b.Navigation("Qualification");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Domain.Models.SavedJob", b =>
                {
                    b.HasOne("Domain.Models.JobPost", "JobPost")
                        .WithMany("SavedJobs")
                        .HasForeignKey("JobPostId")
                        .IsRequired()
                        .HasConstraintName("FK_SavedJob_JobPost");

                    b.HasOne("Domain.Models.JobSeekerProfile", "JobSeekerProfile")
                        .WithMany("SavedJobs")
                        .HasForeignKey("JobSeekerProfileId")
                        .IsRequired()
                        .HasConstraintName("FK_SavedJob_JobSeekerProfile");

                    b.Navigation("JobPost");

                    b.Navigation("JobSeekerProfile");
                });

            modelBuilder.Entity("Domain.Models.AppliedJob", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("Domain.Models.Company", b =>
                {
                    b.Navigation("CompanyUsers");

                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("Domain.Models.Experience", b =>
                {
                    b.Navigation("JobSeekerProfiles");
                });

            modelBuilder.Entity("Domain.Models.Industry", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Domain.Models.JobApplication", b =>
                {
                    b.Navigation("InterviewSchedules");
                });

            modelBuilder.Entity("Domain.Models.JobCategory", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("Domain.Models.JobPost", b =>
                {
                    b.Navigation("AppliedJobs");

                    b.Navigation("JobApplications");

                    b.Navigation("SavedJobs");
                });

            modelBuilder.Entity("Domain.Models.JobProvider", b =>
                {
                    b.Navigation("CompanyUsers");

                    b.Navigation("InterviewSchedules");

                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("Domain.Models.JobSeeker", b =>
                {
                    b.Navigation("JobSeekerProfiles");
                });

            modelBuilder.Entity("Domain.Models.JobSeekerProfile", b =>
                {
                    b.Navigation("AppliedJobs");

                    b.Navigation("SavedJobs");
                });

            modelBuilder.Entity("Domain.Models.JobType", b =>
                {
                    b.Navigation("JobPosts");
                });

            modelBuilder.Entity("Domain.Models.Location", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("JobPosts");

                    b.Navigation("JobSeekerProfiles");
                });

            modelBuilder.Entity("Domain.Models.Qualification", b =>
                {
                    b.Navigation("JobSeekerProfiles");
                });

            modelBuilder.Entity("Domain.Models.Skill", b =>
                {
                    b.Navigation("JobSeekerProfiles");
                });

            modelBuilder.Entity("Domain.Models.SystemUser", b =>
                {
                    b.Navigation("AuthUsers");

                    b.Navigation("JobProviders");

                    b.Navigation("JobSeekers");
                });
#pragma warning restore 612, 618
        }
    }
}
